courses:
  comp: Computing
  jmc:  JMC
  ee:   Electronic Engineering
  ise:  Information System Engineering
  mci:  MSc Computing for Industry
  mres: MRes in Advanced Computing
  msa:  MSc Advanced Computing
  msv:  MSc Computing Science
  mss:  MSs Computing Science Specialism

course_ids:
  comp:
    1:  1
    2:  2
    3:  3
    4:  4
  jmc:
    1:  9
    2:  10
    3:  11
    4:  12
  ee:
    3:  18
    4:  15
  ise:
    1:  5
    2:  6
    3:  7
    4:  8
  mci:
    1:  17
  mres:
    1:  28
  msa:
    1:  14
  msv:
    1:  13
  mss:
    1:  19

seasons:
  - autumn
  - spring
  - summer

week_ranges:
  - !ruby/range 1..1
  - !ruby/range 2..10
  - !ruby/range 11..11
